route:
  receiver: local
  group_by: [alertname, instance]
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: local
    webhook_configs:
      - url: http://alert-receiver:8080/
        send_resolved: true
